<?php

 return [
    [
        'title'=> 'Mountain Chalet Milly',
        'address'=> 'Via di Carpeà, Ledro, TN',
        'user_id'=>3,
        'rooms_n'=>4,
        'beds_n'=>2,
        'bathroom_n'=>1,
        'dimensions'=>85,
        'latitude'=>'45.900383',
        'longitude'=>'10.723176',
        'description'=>'Appartamento su due piani in casa bifamiliare 4 posti letto:
            ampia camera matrimoniale al primo piano ;al piano inferiore cucina ---------superaccessiorata , salotto/soggiorno con divano letto e camino , bagno
            Garage e giardino attrezzato.
            In posizione soleggiata (500 m s.l.m.) dista 5 km da Sondrio.
            Ideale punto d\'appoggio per la pratica di numerosi SPORT come sci /climbing/biking/golf/canoa/tennis trekking ',
        'visible'=>'1',
        'price_per_night'=>155.00,
        'rating'=>4.7,
    ],

    [
        'title'=> 'La Baita Case Suite',
        'address'=>'Via di Castello, Baselga di Piné, TN',
        'user_id'=>3,
        'rooms_n'=>3,
        'beds_n'=>2,
        'bathroom_n'=>1,
        'dimensions'=>60,
        'latitude'=>'46.136155',
        'longitude'=>'10.377523',
        'description'=>'L\'appartamento LaBaitaCase Suite è situato nel centro storico di Sondrio a due passi da Piazza Garibaldi, sede del Teatro Sociale, dal MVSA (Museo Valtellinese di Storia ed Arte) e delle sedi delle Banche locali e non.
         Sono nelle immediate vicinanze bar, ristoranti, negozi, farmacie e i principali servizi.',
        'visible'=>'0',
        'price_per_night'=>119.99,
        'rating'=>4.4,
    ],
    [
        'title'=> 'Loft Caterina',
        'address'=>'Via del Casel, 12, 37010 San Zeno di Montagna VR',
        'user_id'=>3,
        'rooms_n'=>4,
        'beds_n'=>5,
        'bathroom_n'=>2,
        'dimensions'=>105,
        'latitude'=>'45.628597',
        'longitude'=>'10.723611',
        'description'=>'Splendido loft, interamente rivestito in legno caldo, accogliente e luminoso con magnifica vista sulle piste dell\'Abetone.
        Un unico spazio dove è stata ricavata anche una camera matrimoniale separata con bagno en suite. Altro bagno per gli ospiti nel corridoio di ingresso e posti letto in salotto. Cucina piccola ma funzionale.
        Sicuramente un posto ideale dove passare le vacanze in convivialità con la famiglia o gli amici.',
        'visible'=>'0',
        'price_per_night'=>180.00,
        'rating'=>4.6,
    ],
    [
        'title'=> 'La Casa di Alice',
        'address'=>'Strada Provinciale della Grossola, 53023 Castiglione D\'orcia SI',
        'user_id'=>3,
        'rooms_n'=>5,
        'beds_n'=>2,
        'bathroom_n'=>2,
        'dimensions'=>88,
        'latitude'=>'42.970809',
        'longitude'=>'11.563112',
        'description'=>'La Casa di Alice si trova in zona centrale per la visita della Valdorcia
        e Montalcino con sue cantine di Brunello.
        Tutta ristrutturata e molto luminosa, può ospitare da 2 a 4 persone.
        Interamente coperta da Wifi, ha due camere da letto matrimoniali, ciascuna con bagno privato, una cucina accessoriata un soggiorno relax con tv led, poltrone, camino a legna per le fredde sere d\'inverno.
        Riscaldato a energia pulita e restaurato con materiali ecologici.',
        'visible'=>'1',
        'price_per_night'=>175.00,
        'rating'=>4.9,
    ],
    [
        'title'=> 'Ledro Mountain Chalet',
        'address'=>'Via Montecucco, 10, 25083 Gardone Riviera BS',
        'user_id'=>3,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'45.627001',
        'longitude'=>'10.560057',
        'description'=>'Ubicato in una zona tranquilla, a 5 minuti d\'auto da Castelrotto e a 7 km dal comprensorio sciistico Alpe di Siusi, il Christelehof offre appartamenti con angolo cottura e un giardino attrezzato con barbecue e parco giochi per bambini. Dotati di un bagno privato con doccia e asciugamani, gli appartamenti dispongono di una TV a schermo piatto, un balcone, una cassaforte e un angolo cottura completamente accessoriato con lavastoviglie e frigorifero',
        'visible'=>'1',
        'price_per_night'=>220.00,
        'rating'=>5.0,
    ],
    [
        'title'=> 'Sweet Cristallo',
        'address'=>'Corso Italia, 146, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>3,
        'rooms_n'=>1,
        'beds_n'=>1,
        'bathroom_n'=>1,
        'dimensions'=>40,
        'latitude'=>'46.539407',
        'longitude'=>'12.1356',
        'description'=>'In contesto signorile ideale per coppie, coppie di amici/escursionisti,che amano la comodità del centro paese.
        Direttamente sul Corso Italia di Cortina d\'Ampezzo, affitto monolocale tipico ampezzano, con un posto auto in garage.
        Composto da ampio salotto, comodo divano e letto matrimoniale,cucina a gas con 4 fuochi, lavastoviglie, lavello, e tutti gli utensili, tavolo e 2 sedie, piccolo balcone, ampio bagno con vasca doccia e lavatrice.
        ',
        'visible'=>'1',
        'price_per_night'=>150.00,
        'rating'=>5.0,
    ],
    [
        'title'=> 'Comodo chalet nel centro',
        'address'=>'Via dello Stadio, 7/A, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>3,
        'rooms_n'=>2,
        'beds_n'=>4,
        'bathroom_n'=>1,
        'dimensions'=>100,
        'latitude'=>'46.541443',
        'longitude'=>'12.132257',
        'description'=>'L\'appartamento si trova al primo piano a 150 metri dal centro di Cortina e a cinque minuti a piedi dalla stazione. E\' molto comodo anche per chi volesse sciare: ci troviamo a pochi passi dalla Funivia delle Tofane e a pochi minuti dalla Funivia Faloria.
        L\'appartamento, dotato di terrazza, è confortevole e silenzioso.',
        'visible'=>'1',
        'price_per_night'=>40.00,
        'rating'=>4.0,
    ],
    [
        'title'=> 'La Mansarda',
        'address'=>'SR48, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>2,
        'rooms_n'=>3,
        'beds_n'=>2,
        'bathroom_n'=>1,
        'dimensions'=>80,
        'latitude'=>'46.538594',
        'longitude'=>'12.123933',
        'description'=>'Questo appartamento si trova a Cortina d\'Ampezzo - Lacedel. Panoramico su Cortina d\'Ampezzo. A cinque minuti a piedi dalla casa si trova la fermata dell\'autobus locale e le piste sciistiche di Socrepes (area sciistica di Tofana). Al secondo piano (mansardato) ha un soggiorno con zona pranzo, piccola cucina, una camera matrimoniale, una camera con due letti singoli, un bagno, un servizio, una terrazza con splendida vista su Cortina d\'Ampezzo, dove ci si può rilassare. Un posto auto esterno.',
        'visible'=>'1',
        'price_per_night'=>80.00,
        'rating'=>4.2,
    ],
    [
        'title'=> 'Design chalet',
        'address'=>'Via Roma, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>2,
        'rooms_n'=>2,
        'beds_n'=>2,
        'bathroom_n'=>2,
        'dimensions'=>50,
        'latitude'=>'46.530301',
        'longitude'=>'12.140869',
        'description'=>'All\'ultimo piano di un importante edificio degli anni \'50, con magnifica vista sulle Dolomiti d\'Ampezzo, affittiamo monolocale di design arricchito da arredi storici esposti alla XI Triennale di Milano nel \'51.
        Bagno e angolo cottura sono full equipped.',
        'visible'=>'1',
        'price_per_night'=>120.00,
        'rating'=>5.0,
    ],
    [
        'title'=> 'Villa MariaLuisa',
        'address'=>'Via P. F. Calvi, 29, 32046 San Vito di Cadore BL',
        'user_id'=>2,
        'rooms_n'=>3,
        'beds_n'=>8,
        'bathroom_n'=>3,
        'dimensions'=>500,
        'latitude'=>'46.487652',
        'longitude'=>'12.187383',
        'description'=>'Splendida villa appena fuori dal centro di cortina, con bellissima vista sulle dolomiti, disposta su tre piani (utilizzabili anche in maniera indipendente) , tre balconi di cui uno molto spazioso con pranzo e solarium esposto a sud. Gli arredi sono di alto livello ed accoglienti, due sale sono dotate di camino.',
        'visible'=>'1',
        'price_per_night'=>1220.00,
        'rating'=>3.5,
    ],
    [
        'title'=> 'Antique Chalet',
        'address'=>'Strada Statale 51 di Alemagna, 32043 Fiames BL',
        'user_id'=>2,
        'rooms_n'=>1,
        'beds_n'=>1,
        'bathroom_n'=>3,
        'dimensions'=>30,
        'latitude'=>'46.573280',
        'longitude'=>'12.117236',
        'description'=>'Monolocale al piano attico nelle vicinanze del centro di Cortina, 5 minuti a piedi con posto auto in garage.',
        'visible'=>'1',
        'price_per_night'=>120.00,
        'rating'=>5.0,
    ],
    [
        'title'=> 'Elegant Chalet',
        'address'=>'Località Dibona, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>2,
        'rooms_n'=>10,
        'beds_n'=>7,
        'bathroom_n'=>3,
        'dimensions'=>180,
        'latitude'=>'46.540082',
        'longitude'=>'12.092961',
        'description'=>'Appartamento di 180 metri nel centro di Cortina. Dotato di tre camere da letto con tre bagni, cucina e un bel salone',
        'visible'=>'1',
        'price_per_night'=>1500.00,
        'rating'=>5.0,
    ],
    [
        'title'=> 'Rosa Alpina',
        'address'=>'SR48, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>2,
        'rooms_n'=>1,
        'beds_n'=>1,
        'bathroom_n'=>1,
        'dimensions'=>280,
        'latitude'=>'46.550333',
        'longitude'=>'12.183731',
        'description'=>'Chalet Zeno rappresenta il lato migliore dell’hotellerie nelle Dolomiti: l’espressione della tradizione di montagna con qualche spunto moderno.
        Tre lussuose camere doppie, ampio soggiorno con travi a vista, Jacuzzi e sauna finlandese all’aperto. L’essenza della montagna unita all’eleganza del lusso.',
        'visible'=>'1',
        'price_per_night'=>620.00,
        'rating'=>4.5,
    ],
    [
        'title'=> 'Cortina Luxury Chalet',
        'address'=>'SR48, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>2,
        'rooms_n'=>7,
        'beds_n'=>4,
        'bathroom_n'=>3,
        'dimensions'=>320,
        'latitude'=>'46.520886',
        'longitude'=>'12.114591',
        'description'=>'Bellissimo Chalet Luxury di 2 piani di 160 mq a 2 min di macchina dal centro e dagli impianti sciistici di Cortina. Arredato cn legno vecchio di larice e rifinito con arredi di alta qualità e pregio, si compone di3stanze con3bagni ,1grande salotto con divano ad angolo di nobile fattura,1zona da pranzo e una cucina (completa di “Gaggenau", migliore azienda leader del settore) e con zona relax vista montagne il su piano soppalcato in legno mansardato.Disponibile Wi-Fi e domotica su tutta la casa.',
        'visible'=>'1',
        'price_per_night'=>1600.00,
        'rating'=>5,
    ],
    [
        'title'=> 'New Luxury Chalet',
        'address'=>'Strada Statale 48, 1, 32043 Cortina d\'Ampezzo BL',
        'user_id'=>1,
        'rooms_n'=>4,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>200,
        'latitude'=>'46.536544',
        'longitude'=>'12.135993',
        'description'=>'L’edificio, un antico ed affascinante fienile risalente al ‘600, ha mantenuto intatto il suo sapore, attraverso l’uso profuso di legno antico sia all’esterno che all\'interno. Ogni dettaglio è stato studiato con attenzione, per poter vivere l’esperienza unica di alloggiare nell’anima della casa, in un ambiente talmente bello da lasciare senza fiato. Dotato di ogni comfort, per una qualità senza eguali e moderne tecnologie.',
        'visible'=>'1',
        'price_per_night'=>1600.00,
        'rating'=>5,
    ],
    

    [
        'title'=> 'Christelehof Chalet',
        'address'=>'Tisens, 25/1, 39040 Castelrotto BZ',
        'user_id'=>1,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.565701',
        'longitude'=>'11.568871',
        'description'=>'Ubicato in una zona tranquilla, a 5 minuti d\'auto da Castelrotto e a 7 km dal comprensorio sciistico Alpe di Siusi, il Christelehof offre appartamenti con angolo cottura e un giardino attrezzato con barbecue e parco giochi per bambini. Dotati di un bagno privato con doccia e asciugamani, gli appartamenti dispongono di una TV a schermo piatto, un balcone, una cassaforte e un angolo cottura completamente accessoriato con lavastoviglie e frigorifero',
        'visible'=>'1',
        'price_per_night'=>120.00,
        'rating'=>5.0,
    ],

    [
        'title'=> 'Psoar Hof',
        'address'=>'Runggaldier I-39040 Suisi allo Sciliar - ALTO ADIGE (Italia)',
        'user_id'=>1,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.551611',
        'longitude'=>'11.565999',
        'description'=>'Nostro maso si trova in posizione tranquilla a San Valentino sopra Siusi allo Sciliar.
        La fermata dell\'autobus per la cabinovia Siusi-Alpe di Siusi si trova nelle immediate vicinanze.
        Varietà rinfrescante e assoluto relax contraddistinguono l\'estate ai piedi dello Sciliar.
        I più attivi si possono dilettare in conversazioni nel corso di escursioni, ascese alpine, arrampicate, bagni, gite in bicicletta, partite a golf, voli in parapendio o cavalcate.
        Diamo la possibiltà di vivere la quotidiana vita di un maso.
        I piccoli ospiti possono accarrezzare gli animali del nostro maso
        e fare amicizie con loro, divertirsi al prato e nel vicinissimo bosco.',
        'visible'=>'1',
        'price_per_night'=>80.00,
        'rating'=>4.0,
    ],

    [
        'title'=> 'Wegmacherorhof',
        'address'=>'Via Marinzenweg, 33, 39040 Castelrotto BZ',
        'user_id'=>1,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.563531',
        'longitude'=>'11.562444',
        'description'=>'il maso, a cinque minuti di passeggiata dal centro di Castelrotto, è anche punto di partenza per i vari sentieri guidati che si trovano nei dintorni. Il paese è situato sull\'altipiano dello Sciliar, sopra la Valle d\'Isarco e si trova a 1.100 m di altitudine. Per arrivare alle mete, relativamente distanti come quelle di Marinzen, San Valentino, Tisana e Tagusa, i percorsi sono facili e accessibili a tutto il nucleo familiare.
        Affacciandovi al lato sud della casa potrete osservare il maestoso Sciliar con la nota “Punta Santner”. Proseguendo con lo sguardo in senso orario, vi si presenterà l\'imponente sella del Renon, con il “Corno del Renon”. Al lato nord esteso davanti a voi troverete il paese di Castelrotto con il delizioso colle del “Kofl” e la “Rascesa” con la frazione di San Michele.',
        'visible'=>'1',
        'price_per_night'=>110.00,
        'rating'=>4.0,
    ],

    [
        'title'=> 'Chalet Pratesi',
        'address'=>'Str. Pitla Cir,20, 39048 Selva di Val Gardena BZ',
        'user_id'=>1,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.554811',
        'longitude'=>'11.76241',
        'description'=>'Uno dei plus indiscussi dello Chalet Pratesi è la posizione in pieno centro a Selva di Val Gardena. D\'inverno potrete uscire di casa direttamente con gli sci ai piedi e sulle piste da sci della val Gardena e del giro del Sella Ronda.
        Lo Chalet Pratesi è immerso in un ampio giardino privato ad esclusivo utilizzo degli ospiti.  D\'estate i profumi dei prati circostanti vi accompagneranno nelle tante escursioni che questo meraviglioso comprensorio vi offre.
        Un soggiorno memorabile, fuori dal rumore e dal caos.
        Potrete accedere allo Chalet con l\'auto, parcheggiarla nei 3 posti auto privati all\'interno della proprietà, e riprenderla il giorno della partenza.
        La sera, al tramonto, quando le montagne si tingono del tipico colore rosato che le rende uniche al mondo, potrete sorseggiare un aperitivo sull\'ampio terrazzo e sentirvi finalmente a casa.',
        'visible'=>'1',
        'price_per_night'=>170.00,
        'rating'=>4.9,
    ],

    [
        'title'=> 'Chalet L Piz',
        'address'=>'La Selvastrasse, 109, 39048 Selva di Val Gardena',
        'user_id'=>1,
        'rooms_n'=>6,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.551971',
        'longitude'=>'11.728131',
        'description'=>'Uno chalet come lo avete sempre sognato: di architettura moderna, ad uso esclusivo, immerso nella natura. 
        Un ambiente lussuoso con interni eleganti, una vasca idromassaggio sotto il cielo stellato e una vista spettacolare sulle imponenti vette dolomitiche. 
        Lo Chalet L Piz è l\'alloggio ideale per chi vuole godersi 80 m2 di pura felicità in totale privacy ai piedi del Sassolungo in Val Gardena. 
        In inverno potrete partire direttamente dallo chalet con gli sci ai piedi, poiché vi troverete direttamente sulla pista di Coppa del Mondo Saslong e quindi sul Sellaronda. In estate il nostro chalet si trova nelle vicinanze dei sentieri escursionistici ed è il punto di partenza ideale per intraprendere escursioni e tour in mountain bike di ogni livello di difficoltà. Godetevi appieno una vacanza estiva o invernale nel nostro chalet da sogno nelle Dolomiti, Patrimonio Mondiale dell\'Umanità.',
        'visible'=>'1',
        'price_per_night'=>190.00,
        'rating'=>5.0,
    ],

    [
        'title'=> 'Chalet Gerard',
        'address'=>'Str. Plan de Gralba, 37,39048 Selva di Val Gardena BZ',
        'user_id'=>1,
        'rooms_n'=>2,
        'beds_n'=>3,
        'bathroom_n'=>2,
        'dimensions'=>120,
        'latitude'=>'46.536401',
        'longitude'=>'11.778891',
        'description'=>'Là dove volano le aquile, e il cielo sembra più vicino, si aprono le porte di Chalet Gerard - The Mountain Lodge, prezioso boutique hotel a Selva di Val Gardena, splendidamente integrato nella natura e nel paesaggio che lo circonda, una finestra affacciata sulle incantevoli cime del Gruppo Sella e Sassolungo.
        Nato dal sogno e dalla passione della famiglia Mussner, Chalet Gerard è un nido accogliente in cui la montagna "si respira" nei toni caldi delle lane cotte, nell\'abbraccio naturale del larice, nei preziosi ricordi di papà Gerard che riportano indietro nel tempo.
        Le linee morbide dell\'architettura, il moderno caminetto e le luci soffuse ne fanno un mountain lodge di grande atmosfera, fatto di contemporaneità e tradizione, calore e ospitalità… profumo di cirmolo e di canederli!  
        Vi aspettiamo per la vostra prossima vacanza all\'Hotel Chalet Gerard in Val Gardena!',
        'visible'=>'1',
        'price_per_night'=>320.00,
        'rating'=>5.0,
    ],



 ] ?>